version: '3'

services:
  server:
    container_name: songee-app
    build: 
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  postgres:
    image: postgres
    restart: always
    environment: 
        - DATABASE_HOST=127.0.0.1
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=root  

    ports: 
        - "5432:5432"
    volumes: 
        - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

networks:
  postgres-network:
    driver: bridge